/*
* generated by Xtext
*/
package org.dslengineering.p3demo.ui.contentassist;

import org.dslengineering.p3demo.ui.contentassist.AbstractP3DemoDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class P3DemoDslProposalProvider extends AbstractP3DemoDslProposalProvider {

}
