/*
 * generated by Xtext
 */
package org.dslengineering.p3demo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class P3DemoDslUiModule extends org.dslengineering.p3demo.ui.AbstractP3DemoDslUiModule {
	public P3DemoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
