/*
 * generated by Xtext
 */
package org.dslengineering.p3demo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class P3DemoDslRuntimeModule extends org.dslengineering.p3demo.AbstractP3DemoDslRuntimeModule {

}
