/*
* generated by Xtext
*/
package org.dslengineering.p3demo.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class P3DemoDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
